version: '3.8'

services:
  postgress:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER:rushali
      POSTGRES_PASSWORD:Pass@123
      POSTGRES_DB:School
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app :
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://rushali:Pass@123@localhost:5432/School
    depends_on:
      - postgress